### ISSUE TITLE
[MODULE] - IBAN extraction

### ISSUE THREAD

**Issue by divyanshukatiyar** [code-kern-ai/bricks#143]
**Description**
I want to extract all the IBAN details from a text document. For this, regular expressions can be used since the IBAN can vary from bank to bank and country to country.

**Implementation**

```python
import re
import spacy

text = "My IBAN is DE123456789876543210"
nlp = spacy.load("en_core_web_sm")
doc = nlp(text)
regex = re.compile(r"[A-Z]{2}\d{2} ?\d{4} ?\d{4} ?\d{4} ?\d{4} ?[\d]{0,2}")

iban = []
for match in regex.finditer(text):
    start, end = match.span()
    span = doc.char_span(start, end)
    iban.append([span.start, span.end, "IBAN"])

print(iban)
```

**Additional context**

**Comment by jhoetter** [comment]
@divyanshukatiyar the endpoint of this returns values in wrong format. It returns them in index-index-label, but it should be label-index-index

**Comment by LeonardPuettmann** [comment]
Seems to be fixed, closing now,
