### ISSUE TITLE
[MODULE] - Domain name parser

### ISSUE THREAD

**Issue by divyanshukatiyar** [code-kern-ai/bricks#148]
**Description**
In a given text I have a number of links from which I wish to create a separate table consisting only of the root domain names. 

**Do you already have an implementation?**
If so, please share it here.

**Additional context**

**Comment by LeonardPuettmannKern** [comment]
Just noticed that the docstring for the function in the __init__.py went missing. Will fix that. :)

**Comment by LeonardPuettmannKern** [comment]
Fixed with #312
