### ISSUE TITLE
[MODULE] - VADER Sentiment classification

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/bricks#157]
**Please describe the module you would like to add to bricks**
Either go in detail, or just share a sketch of an idea here

**Do you already have an implementation?**
```python 
 import SentimentIntensityAnalyzer class
# from vaderSentiment.vaderSentiment module.
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
 
# function to print sentiments
# of the sentence.
def sentiment_scores(sentence):
 
    # Create a SentimentIntensityAnalyzer object.
    sid_obj = SentimentIntensityAnalyzer()
 
    # polarity_scores method of SentimentIntensityAnalyzer
    # object gives a sentiment dictionary.
    # which contains pos, neg, neu, and compound scores.
    sentiment_dict = sid_obj.polarity_scores(sentence)
     
    print("Overall sentiment dictionary is : ", sentiment_dict)
    print("sentence was rated as ", sentiment_dict['neg']*100, "% Negative")
    print("sentence was rated as ", sentiment_dict['neu']*100, "% Neutral")
    print("sentence was rated as ", sentiment_dict['pos']*100, "% Positive")
 
    print("Sentence Overall Rated As", end = " ")
 
    # decide sentiment as positive, negative and neutral
    if sentiment_dict['compound'] >= 0.05 :
        print("Positive")
 
    elif sentiment_dict['compound'] <= - 0.05 :
        print("Negative")
 
    else :
        print("Neutral")
```

**Additional context**
https://github.com/cjhutto/vaderSentiment

**Comment by LeonardPuettmann** [comment]
Implemented with #216

**Comment by jhoetter** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62521561/214694502-cd5733b3-e5d6-4a22-9941-8f23281010d6.png">

@LeonardPuettmann  I'm a bit confused, what's up with this "scores" implementation? That isn't really a classifier from our definition then, is it?

**Comment by LeonardPuettmann** [comment]
@jhoetter Well, if you set it to "classification" then yes it is. :) 
I thought that it might be nice to allow users to just set a switch to either get a string or the numeric scores. But I can remove that functionality if you think it's too confusing!
