### ISSUE TITLE
[MODULE] - URL parser

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/bricks#163]
**Please describe the module you would like to add to bricks**
Given a URL, I want to extract certain parts of the URL, such as the host, a path or a query.

**Do you already have an implementation?**
```python
from yarl import URL
url = URL('https://www.python.org/~guido?arg=1#frag')
```

**Additional context**
The yarl library might be useful for this. https://github.com/aio-libs/yarl/

**Comment by jhoetter** [comment]
isn't this the same as #40?

**Comment by LeonardPuettmann** [comment]
No. #40 Extracts whole URLs, while this lib parses specific parts of a URL.

**Comment by LeonardPuettmannKern** [comment]
Closing as issue was fixed
