### ISSUE TITLE
[BUG] - Undefined variable in zip code extraction refinery snipped

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/bricks#180]
## What module did you encounter a bug with?
extractors/python_functions/**zipcode_extraction**

## Please describe the bug you observed with this module.
The refinery code has an undefined variable throwing errors.
```Traceback (most recent call last):
File "//run_ide.py", line 15, in <module>
exec(code)
File "<string>", line 182, in <module>
File "<string>", line 182, in <listcomp>
File "<string>", line 12, in zipcode_extraction
NameError: name 'zip_codes_json' is not defined
```

## Do you already have a fix for that?
rename `zip_codes` to `zip_codes_json`

## Additional context
-

**Comment by LeonardPuettmann** [comment]
Uppdated code, issue resolved

**Comment by DerEchteFeuerpfeil** [comment]
Okay the code was already changed in #166, was a cms related issue
