### ISSUE TITLE
Icons for bricks

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/bricks#189]
We should add icons to each brick in the config file, precisely via [tabler-icons](https://tabler-icons.io/).

For instance, I want to include the `translate` icon in the language translation (#81) brick.

![image](https://user-images.githubusercontent.com/62521561/208888426-b29d637e-e3f0-4334-8c63-6053b8fab12f.png)

(each tabler icon has a unique name)

In the `config.py` file, we could add something like `icon`, e.g.:

```python
def get_config():
    return build_generator_function_config(
        function=language_translator,
        input_example=INPUT_EXAMPLE,
        data_type="text",
        issue_id=81,  
        icon="translate", # THIS IS NEW
        state=State.PUBLIC
    )
```

**Comment by LeonardPuettmann** [comment]
Is this already configured or does this still need to be built?

**Comment by jhoetter** [comment]
not configured yet. Would be great for the website though. Will look into it :)
