### ISSUE TITLE
[MODULE] - GPT3 TL;DR summarisation

### ISSUE THREAD

**Issue by divyanshukatiyar** [code-kern-ai/bricks#195]
**Description**
A module that summarises long texts in 4-5 lines using gpt3 "text-davinci-003" model.

**Additional context**
Premium function, **requires an api key**.

**Comment by LeonardPuettmann** [comment]
The code snippet needs to be updated to only return the text

**Comment by LeonardPuettmann** [comment]
Updated the source code
