### ISSUE TITLE
[MODULE] - GPT3-based restaurant review generator

### ISSUE THREAD

**Issue by divyanshukatiyar** [code-kern-ai/bricks#202]
**Please describe the module you would like to add to bricks**
I wish to generate the reviews for a restaurant by only inputing the keywords like the name of the restaurant, the dishes served, the ambience, how expensive it was, quality of food, etc. This can be achieved by using the GPT3 model.

**Do you already have an implementation?**
-

**Additional context**
-

**Comment by LeonardPuettmann** [comment]
Implemented with #203

**Comment by LeonardPuettmann** [comment]
The code snippet needs to be updated to only return the text

**Comment by LeonardPuettmann** [comment]
Updated the source code
