### ISSUE TITLE
[UX] - The template for the Bug Report could be misleading

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/bricks#205]
The following lines of the template for a Bug Report could be misleading.
```
## What module did you encounter a bug with?
Please specify the full path to the module.

For example: "extractor/python_functions/color_code_extraction".
```
For users who don't know the repository structure of bricks, it could be unclear what it means.
To minimize the effort, we could ask for a link to the module on bricks.kern.ai.
An alternative would be to ask for the module type and name to identify it.

**Comment by LeonardPuettmannKern** [comment]
Updated this. Thanks for the hint. 👍
