### ISSUE TITLE
[MODULE] - Google (or any other) search engine enrichment

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/bricks#206]
**Please describe the module you would like to add to bricks**
E.g. for product data, I want to enrich the first N free text result of a search engine (let's say I input "sony monitor gaming", I want to get 
```
INZONE M9 | 27 Zoll 4K HDR-Gaming-Monitor mit 144 Hz, IPS 1 ms ... Entdecken Sie eine Welt brillanter Details. Mit unserem INZONE M9 Gaming-Monitor mit 4K HDR, ...
```

(this is my first result of the google search)

Why? because this could be really interesting for classifying and standardizing products into categories :-) 

**Do you already have an implementation?**
I used to build this with a simple python request and beautifulsoup. Keep in mind though that you must add some delay for the search (or use some logic to alter the IP, maybe this can be done via VPN?), else you get client errors. There are actually companies doing that, and the category is called SERP (https://mailchimp.com/marketing-glossary/serp/#:~:text=Results%20Page%20(SERP)-,Search%20Engine%20Results%20Page%20(SERP),%2Dclick%20(PPC)%20ads.)

**Additional context**
\-

**Comment by LeonardPuettmann** [comment]
Google and Bing offer APIs for this. Although Googles API is quite expansive.

**Comment by jhoetter** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/62521561/214694087-ff1fbbc7-e64e-4f91-a5f9-768c65b8b642.png">
@LeonardPuettmann @divyanshukatiyar I think the current description doesn't really help users _which_ API key they have to insert. Could you make sure for premium functions that the description gives a hint about the API key? :)
