### ISSUE TITLE
[MODULE] - Syllable count

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/bricks#21]
**Please describe the module you would like to add to the content library**
Counts the syllables in a string.

**Do you already have an implementation?**
```python
from typing import Dict, Any
import textstat

def fn_syllable_count(record: Dict[str, Any]):
    text = record["text]
    syllables = textstat.syllable_count(text)
    return {"time": syllables}
```

**Additional context**

**Comment by jhoetter** [comment]
I think that the sample input is wrong :D 
```json
{
    "text": "This sentence has 7 syllables."
}
```
aren't those 8?

**Comment by LeonardPuettmann** [comment]
True! Looks like I badly needed that syllable counter. Phew!
