### ISSUE TITLE
[MODULE] - Manhattan distance

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/bricks#231]
**Please describe the module you would like to add to bricks**
I would like to have a module that calculates the manhattan distance between two vectors.

**Do you already have an implementation?**
If so, please share it here. For instance:
```python
def manhattan(vector_one, vector_two):
    return sum(abs(val1-val2) for val1, val2 in zip(vector_one, vector_two))
```

**Additional context**

**Comment by LeonardPuettmannKern** [comment]
added with #262
