### ISSUE TITLE
[MODULE] - HTML Special Char Replace

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/bricks#233]
**Please describe the module you would like to add to bricks**
When I load an HTML email, and it doesn't encode the data correctly, I can get messages such as the following: `
Here&#39;s how &quot;Kern.ai Newsletter&quot; did today.`
As you can imagine, I'd much rather have: `Here's how "Kern.ai Newsletter" did today.`

**Do you already have an implementation?**
no, but a simple lookup in a dictionary would do the job :)

**Additional context**
\-

**Comment by rasdani** [comment]
Will tackle this with `html.unescape()` 👍

**Comment by rasdani** [comment]
PR #269

**Comment by LeonardPuettmannKern** [comment]
Thanks @rasdani ! Implemented with #269
