### ISSUE TITLE
[MODULE] - Annotator split / random int generator

### ISSUE THREAD

**Issue by LeonardPuettmannKern** [code-kern-ai/bricks#280]
**Please describe the module you would like to add to bricks**
A simple function that uses the random library to return a random integer. This can be used to then split data for different annotators.

**Do you already have an implementation?**
```python
import random
def annotator_split(record):
    n_annotators = 5
    return random.randint(0, n_annotators-1)
```

**Additional context**
This would be a generator brick module.

**Comment by jhoetter** [comment]
super simple, but really helpful as an attribute function to split data slices. I love it! Generally, we could look into grouping bricks into splits for annotation with the newly gained partOfGroups. I'm thinking for instance that
- language
- sentence complexity
- reading time

could all be part of that group :)

**Comment by SvenjaKern** [comment]
I wrote a module for it :)
