### ISSUE TITLE
[MODULE] - ISBN extraction

### ISSUE THREAD

**Issue by divyanshukatiyar** [code-kern-ai/bricks#29]
**Description**
This module extracts all the serials corresponding to the **International Standard Book Number** (ISBN) from a given text. This however, does not validate the ISBN. Generally, an ISBN is 10 digits long (if assigned before 2007), or 13 digits long (if assigned from January 1st, 2007) with numbers separated by hyphens. There is a fixed format for the ISBN number:
10 digits: **X-XXXX-XXXX-X**
13 digits: **XXX-X-XXXX-XXXX-X**

**Implementation**
```python
from typing import Dict
import spacy
import re

def isbn_extractor(text: str = None) -> Dict:
    if text is None:
        text = "I wish to have this book issued. It's ISBN number is 978-2-0074-4301-1."
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    regex = re.compile(r"(?:[\d-]{17}|[\d-]{13})")

    isbn = []
    for match in regex.finditer(text):
        start, end = match.span()
        span = doc.char_span(start, end)
        isbn.append([span.start, span.end, span.text])

    return {"isbn": isbn}
```

**Important requirements**

- Make sure to have **spacy** installed if running on the local machine. It can be installed using `pip install -U spacy`.
- The `en_core_web_sm` tokenizer is needed which can be installed by running `python -m spacy download en_core_web_sm` on the terminal.

**Comment by jhoetter** [comment]
@divyanshukatiyar the endpoint has a faulty response schema
