### ISSUE TITLE
[MODULE] - Email attachment scanner pdf

### ISSUE THREAD

**Issue by SvenjaKern** [code-kern-ai/bricks#329]
**Please describe the module you would like to add to bricks**
A lot of attachments contain relevant information - especially pdf.
There are some PDF-to-text-scanner, which we could try out. 

**Do you already have an implementation?**
That might be a start:
```python
from PyPDF2 import PdfReader
reader = PdfReader('example.pdf')
text = page.extract_text()
print(text)
```

**Comment by SvenjaKern** [comment]
I made a first attempt for that brick.

**Comment by jhoetter** [comment]
bricks currently doesn't include PDF transformations, i.e. input currently must be text.
We can look into this again as soon as we allow different input formats. I'll label this :-) For now, closed though
