### ISSUE TITLE
[ENH] - Language detection failsafe

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/bricks#342]
## What module would you like to enhance?
[Language detection](https://github.com/code-kern-ai/bricks/issues/1) should have some kind of failsafe for empty texts.
Currently an empty record attribute results in an error.

For example: 
![image (1)](https://github.com/code-kern-ai/bricks/assets/91723236/4121a834-3d5f-4da5-9ae0-36d5d7f77e2a)

## Do you already have an implementation for that?
For example:

```python
from langdetect import detect

ATTRIBUTE: str = "reference" #only text attributes

def attribute_6(record):
    text = record[ATTRIBUTE].text # SpaCy document, hence we need to call .text to get the string
    if not text or not text.strip():
        return "unknown"
    return detect(text) # e.g. "en"
  ```

Another option would be to wrap it into a try: catch: block

**Comment by LeonardPuettmannKern** [comment]
Implemented with #366
