### ISSUE TITLE
[MODULE] - Question type classifier (ML model)

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/bricks#344]
**Please describe the module you would like to add to bricks**
Depending what kind of query/question type you have, you might need different search approaches; so detecting the type of query can be helpful to e.g. prioritize in retrieval. Some examples:

**Keyword-query:**
"Italian restaurants"
"Winter boots sale"
"SpaceX latest launch"
"Chocolate cake recipe"
"Jazz festivals 2023"

**Interrogative-query:**
"How do you make a sourdough starter?"
"When was the Declaration of Independence signed?"
"Who wrote the novel 'Pride and Prejudice'?"
"Where can I find the best sushi in Tokyo?"
"Why do leaves change color in the fall?"

**Statement-query:**
"Tell me about the history of the Eiffel Tower."
"Show me the weather forecast for New York next week."
"I want to know more about quantum physics."
"Give me options for vegetarian dinner recipes."
"I'm looking for books written by Jane Austen."

**Do you already have an implementation?**
The keyword classifier can be implemented by removing stopwords and seeing if the length of the sentence changed (significantly). Interrogative is rather "Why", "When", "How", "Where" and "Who".

**Additional context**
We will have multiple bricks for this; this one here is the ML classifier.

**Comment by jhoetter** [comment]
Keep in mind, we want this to work for English and German (and other languages of course as well, in the future). One approach could be e.g. language-specific keywords or language-specific stopwords-removal, or a multilingual embedding with a classifier hosted on eg. HF

**Comment by LeonardPuettmannKern** [comment]
Implemented with #373
