### ISSUE TITLE
[MODULE] - Tiktoken Length Classifier

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/bricks#347]
**Please describe the module you would like to add to bricks**
See here: https://platform.openai.com/tokenizer

**Do you already have an implementation?**
Tiktoken has a basic implementation in their docs, e.g. for gpt-3.5.-turbo. We just need to calculate the number of tokens of a text input.

**Additional context**
Also use this to calculate the complexity of a paragraph for RAG; for instance, > 1000 tokens means a high complexity.

**Comment by jhoetter** [comment]
Those are two bricks, if I think about it. one to just calculate the number of tokens (i.e. returning an integer), and one brick that categorizes the text into discrete classes like "short", "medium", "long" etc.

**Comment by LeonardPuettmannKern** [comment]
@jhoetter I will rename this issue to "Tiktoken Length Classifier" and open a separate issue for a "Tiktoken Token Counter" generator brick!

**Comment by LeonardPuettmannKern** [comment]
See here: https://github.com/code-kern-ai/bricks/issues/359

**Comment by LeonardPuettmannKern** [comment]
Implemented with #360
