### ISSUE TITLE
[MODULE] - Grouped/Window Sentence Complexity

### ISSUE THREAD

**Issue by jhoetter** [code-kern-ai/bricks#351]
**Please describe the module you would like to add to bricks**
The [sentence complexity brick](https://github.com/code-kern-ai/bricks/issues/2) is really cool, but a disadvantage is that the longer a paragraph is, the more likely it falls into a "complex" classification - even if the overall paragraph is super simple and straightforward. I recommend we implement a version that e.g. chunks the text into partitions (e.g. using the spacy.sents, or splitting by "\n"), and then calculating the complexity per sentence.

We could use this to e.g. create the mode complexity, or maximum complexity.

**Do you already have an implementation?**
Use the logic of the [sentence complexity brick](https://github.com/code-kern-ai/bricks/issues/2), but add some logic to group this by sentence and then apply some aggregation logic

**Additional context**
\-

**Comment by LeonardPuettmannKern** [comment]
Closing, added with #363
