### ISSUE TITLE
[MODULE] - Location/Address extraction

### ISSUE THREAD

**Issue by divyanshukatiyar** [code-kern-ai/bricks#62]
**Description**
This module extracts the street addresses from a given text. For this, we use regular expressions that traces a particular address format from the text and extracts it. The valid formats, for example, are - "40 Downing Street, Cardiff ME19 7DY, Wales", or "Hirschberger Straße 64, 53119 Bonn, Germany". The most important thing to notice is the structuring of these formats:
**Case 1**: [Nr.] [Street name], [City] [Postal code], [Country]
**Case 2**: [Street name] [Nr.], [Postal code] [City], [Country]

Grammatically, both of the formats also assume that there will be a period at the end of the complete address.

**Implementation**
```python
from typing import Dict
import re
import spacy

def location(text: str = None) -> Dict:
    if text is None:
        text = "I live at 35 Wood Lane, Pilsbury ME19 7DY, United Kingdom. But I have also lived at 221BE Baker-callum Street, London VIC 3SX, United Kingdom."
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    regex_1 = re.compile(r"(?:\d{1,5}(?:[A-Z ]+[ ]?)+(?:[A-Za-z-]+[ ]?)+(?:Avenue|Lane|Road|Boulevard|Drive|Street|Ave|Dr(?:\.)?|Rd(?:\.)?|Blvd(?:\.)?|Ln(?:\.)?|St(?:\.)?|Strasse|Hill|Alley|Alle|City)[,](?:[ A-Za-z0-9,]+[ ]?)?)")
    regex_2 = re.compile(r"(?:(?:[A-Za-z-]?)+[ ](?:Avenue|Lane|Road|Boulevard|Drive|Street|Ave|Dr(?:\.)?|Rd(?:\.)?|Blvd(?:\.)?|Ln(?:\.)?|St(?:\.)?|Strasse|Str(?:\.)?|Hill|Alley|Alle|City)[ ]+\d{1,5},(?:[ A-Za-z0-9,]+[ ]?)?)")
    addresses = []

    if regex_1.findall(text):
        for match in regex_1.finditer(text):
            start, end = match.span()
            span = doc.char_span(start, end)
            addresses.append([span.start, span.end, span.text])
    if regex_2.findall(text):
        for match in regex_2.finditer(text):
            start, end = match.span()
            span = doc.char_span(start, end)
            addresses.append([span.start, span.end, span.text])

    return {"addresses": addresses}
```

**Additional information**
The address formats can vary differently and can be very dynamic from text to text. This module is not expected to work 100% of the times yet, for example, if the address is parsed in a new format for which the regular expression is not created yet. In that case, the new format can be discussed on this github issue and a regex can be created and integrated in the module.

Also, make sure that **SpaCy** is installed if running on the local machine since we need to create a spacy doc object from the text which is just a sequence of tokens.

**Comment by jhoetter** [comment]
Hi @divyanshukatiyar 

This one seems to have a faulty response for the endpoint (same as #67)

**Comment by jhoetter** [comment]
I.e. it returns 4 values, whereas only 4 are expected
