### ISSUE TITLE
[MODULE] - Longest Common Substring

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/bricks#78]
**Please describe the module you would like to add to bricks**
The LCS is a common example of character-based similarity measure. Given two strings, s1 of length n1 and s2 of length n2, it simply considers the length of the longest string (or strings) which is substring of both s1 and s2.

**Do you already have an implementation?**
If so, please share it here. For instance:
```python
def LCS(s1, s2): 
    n1, n2, res = len(s1), len(s2), 0
    LCSubstring = [[0 for c in range(n2 + 1)] for r in range(n1 + 1)]
    for i in range(n1 + 1):
        for j in range(n2 + 1):
            if (i == 0 or j == 0):
                LCSubstring[i][j] = 0
            elif (s1[i-1] == s2[j-1]):
                LCSubstring[i][j] = LCSubstring[i-1][j-1] + 1
                res = max(res, LCSubstring[i][j])
            else: LCSubstring[i][j] = 0
    return res
```

**Additional context**
Applications: data deduplication and plagiarism detection.

**Comment by jhoetter** [comment]
@LeonardPuettmann the endpoint schema of this one seems faulty, it only returns the indices, not the label itself (only on the playground)
