### ISSUE TITLE
[MODULE] - Toxicity detection

### ISSUE THREAD

**Issue by LeonardPuettmann** [code-kern-ai/bricks#80]
**Please describe the module you would like to add to bricks**
Detect toxic, spam or hateful messages or comments. Could be further broken down into atomic modules, e.g. one module for detecting racism, one for detecting general hate speech etc.

**Do you already have an implementation?**
-

**Additional context**
-

**Comment by rasdani** [comment]
Can take a shot at this with https://huggingface.co/unitary/toxic-bert

**Comment by rasdani** [comment]
PR #271

**Comment by LeonardPuettmannKern** [comment]
Implemented with #271 , thanks @rasdani !

**Comment by jhoetter** [comment]
@LeonardPuettmannKern just wondering, is this really a generator? As this produces labels i could directly have in a labeling task. Close the issue if i opened it again for the wrong reason, just was wondering :)

**Comment by LeonardPuettmannKern** [comment]
@jhoetter In its current form, it's not returning a label only, so it's definitely a generator. :) What we can do is split this brick up into one that returns the score values (as it does atm) and one that returns labels (ie a classifier). We did a similar thing with the VADER sentiment modules #157 #276 

I'll close this issue and reopen a new issue for the classifier brick.
